### ISSUE TITLE
Create widget(s)

### ISSUE THREAD

**Issue by phlippieb** [phlippieb/daily-budget-app#60]
## Info

- Intro to creating a widget: https://developer.apple.com/documentation/widgetkit/creating-a-widget-extension/
- Mark as sensitive: 
   > To let people decide whether a widget should show sensitive data on a locked device, mark views that contain sensitive information using the [privacySensitive(_:)](https://developer.apple.com/documentation/SwiftUI/View/privacySensitive(_:)) modifier
- Supporting multiple widgets: https://developer.apple.com/documentation/SwiftUI/WidgetBundle

## Tasks

- [x] Create designs using dummy data
- [x] Use live data
- [x] Support mark as sensitive
- [x] Create "what's new" thing and let existing users know about widgets — broken off into new task [#69](https://github.com/phlippieb/daily-budget-app/issues/69)
